# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/diogocosta/usask/openwq/openwq

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/diogocosta/usask/openwq/openwq

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/diogocosta/usask/openwq/openwq/CMakeFiles /Users/diogocosta/usask/openwq/openwq//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/diogocosta/usask/openwq/openwq/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openwq

# Build rule for target.
openwq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 openwq
.PHONY : openwq

# fast build rule for target.
openwq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/build
.PHONY : openwq/fast

src/OpenWQ_chem.o: src/OpenWQ_chem.cpp.o
.PHONY : src/OpenWQ_chem.o

# target to build an object file
src/OpenWQ_chem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_chem.cpp.o
.PHONY : src/OpenWQ_chem.cpp.o

src/OpenWQ_chem.i: src/OpenWQ_chem.cpp.i
.PHONY : src/OpenWQ_chem.i

# target to preprocess a source file
src/OpenWQ_chem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_chem.cpp.i
.PHONY : src/OpenWQ_chem.cpp.i

src/OpenWQ_chem.s: src/OpenWQ_chem.cpp.s
.PHONY : src/OpenWQ_chem.s

# target to generate assembly for a file
src/OpenWQ_chem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_chem.cpp.s
.PHONY : src/OpenWQ_chem.cpp.s

src/OpenWQ_initiate.o: src/OpenWQ_initiate.cpp.o
.PHONY : src/OpenWQ_initiate.o

# target to build an object file
src/OpenWQ_initiate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_initiate.cpp.o
.PHONY : src/OpenWQ_initiate.cpp.o

src/OpenWQ_initiate.i: src/OpenWQ_initiate.cpp.i
.PHONY : src/OpenWQ_initiate.i

# target to preprocess a source file
src/OpenWQ_initiate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_initiate.cpp.i
.PHONY : src/OpenWQ_initiate.cpp.i

src/OpenWQ_initiate.s: src/OpenWQ_initiate.cpp.s
.PHONY : src/OpenWQ_initiate.s

# target to generate assembly for a file
src/OpenWQ_initiate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_initiate.cpp.s
.PHONY : src/OpenWQ_initiate.cpp.s

src/OpenWQ_output.o: src/OpenWQ_output.cpp.o
.PHONY : src/OpenWQ_output.o

# target to build an object file
src/OpenWQ_output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_output.cpp.o
.PHONY : src/OpenWQ_output.cpp.o

src/OpenWQ_output.i: src/OpenWQ_output.cpp.i
.PHONY : src/OpenWQ_output.i

# target to preprocess a source file
src/OpenWQ_output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_output.cpp.i
.PHONY : src/OpenWQ_output.cpp.i

src/OpenWQ_output.s: src/OpenWQ_output.cpp.s
.PHONY : src/OpenWQ_output.s

# target to generate assembly for a file
src/OpenWQ_output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_output.cpp.s
.PHONY : src/OpenWQ_output.cpp.s

src/OpenWQ_readjson.o: src/OpenWQ_readjson.cpp.o
.PHONY : src/OpenWQ_readjson.o

# target to build an object file
src/OpenWQ_readjson.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_readjson.cpp.o
.PHONY : src/OpenWQ_readjson.cpp.o

src/OpenWQ_readjson.i: src/OpenWQ_readjson.cpp.i
.PHONY : src/OpenWQ_readjson.i

# target to preprocess a source file
src/OpenWQ_readjson.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_readjson.cpp.i
.PHONY : src/OpenWQ_readjson.cpp.i

src/OpenWQ_readjson.s: src/OpenWQ_readjson.cpp.s
.PHONY : src/OpenWQ_readjson.s

# target to generate assembly for a file
src/OpenWQ_readjson.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_readjson.cpp.s
.PHONY : src/OpenWQ_readjson.cpp.s

src/OpenWQ_sinksource.o: src/OpenWQ_sinksource.cpp.o
.PHONY : src/OpenWQ_sinksource.o

# target to build an object file
src/OpenWQ_sinksource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_sinksource.cpp.o
.PHONY : src/OpenWQ_sinksource.cpp.o

src/OpenWQ_sinksource.i: src/OpenWQ_sinksource.cpp.i
.PHONY : src/OpenWQ_sinksource.i

# target to preprocess a source file
src/OpenWQ_sinksource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_sinksource.cpp.i
.PHONY : src/OpenWQ_sinksource.cpp.i

src/OpenWQ_sinksource.s: src/OpenWQ_sinksource.cpp.s
.PHONY : src/OpenWQ_sinksource.s

# target to generate assembly for a file
src/OpenWQ_sinksource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_sinksource.cpp.s
.PHONY : src/OpenWQ_sinksource.cpp.s

src/OpenWQ_solver.o: src/OpenWQ_solver.cpp.o
.PHONY : src/OpenWQ_solver.o

# target to build an object file
src/OpenWQ_solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_solver.cpp.o
.PHONY : src/OpenWQ_solver.cpp.o

src/OpenWQ_solver.i: src/OpenWQ_solver.cpp.i
.PHONY : src/OpenWQ_solver.i

# target to preprocess a source file
src/OpenWQ_solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_solver.cpp.i
.PHONY : src/OpenWQ_solver.cpp.i

src/OpenWQ_solver.s: src/OpenWQ_solver.cpp.s
.PHONY : src/OpenWQ_solver.s

# target to generate assembly for a file
src/OpenWQ_solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_solver.cpp.s
.PHONY : src/OpenWQ_solver.cpp.s

src/OpenWQ_units.o: src/OpenWQ_units.cpp.o
.PHONY : src/OpenWQ_units.o

# target to build an object file
src/OpenWQ_units.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_units.cpp.o
.PHONY : src/OpenWQ_units.cpp.o

src/OpenWQ_units.i: src/OpenWQ_units.cpp.i
.PHONY : src/OpenWQ_units.i

# target to preprocess a source file
src/OpenWQ_units.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_units.cpp.i
.PHONY : src/OpenWQ_units.cpp.i

src/OpenWQ_units.s: src/OpenWQ_units.cpp.s
.PHONY : src/OpenWQ_units.s

# target to generate assembly for a file
src/OpenWQ_units.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_units.cpp.s
.PHONY : src/OpenWQ_units.cpp.s

src/OpenWQ_watertransp.o: src/OpenWQ_watertransp.cpp.o
.PHONY : src/OpenWQ_watertransp.o

# target to build an object file
src/OpenWQ_watertransp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_watertransp.cpp.o
.PHONY : src/OpenWQ_watertransp.cpp.o

src/OpenWQ_watertransp.i: src/OpenWQ_watertransp.cpp.i
.PHONY : src/OpenWQ_watertransp.i

# target to preprocess a source file
src/OpenWQ_watertransp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_watertransp.cpp.i
.PHONY : src/OpenWQ_watertransp.cpp.i

src/OpenWQ_watertransp.s: src/OpenWQ_watertransp.cpp.s
.PHONY : src/OpenWQ_watertransp.s

# target to generate assembly for a file
src/OpenWQ_watertransp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/OpenWQ_watertransp.cpp.s
.PHONY : src/OpenWQ_watertransp.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openwq.dir/build.make CMakeFiles/openwq.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... openwq"
	@echo "... src/OpenWQ_chem.o"
	@echo "... src/OpenWQ_chem.i"
	@echo "... src/OpenWQ_chem.s"
	@echo "... src/OpenWQ_initiate.o"
	@echo "... src/OpenWQ_initiate.i"
	@echo "... src/OpenWQ_initiate.s"
	@echo "... src/OpenWQ_output.o"
	@echo "... src/OpenWQ_output.i"
	@echo "... src/OpenWQ_output.s"
	@echo "... src/OpenWQ_readjson.o"
	@echo "... src/OpenWQ_readjson.i"
	@echo "... src/OpenWQ_readjson.s"
	@echo "... src/OpenWQ_sinksource.o"
	@echo "... src/OpenWQ_sinksource.i"
	@echo "... src/OpenWQ_sinksource.s"
	@echo "... src/OpenWQ_solver.o"
	@echo "... src/OpenWQ_solver.i"
	@echo "... src/OpenWQ_solver.s"
	@echo "... src/OpenWQ_units.o"
	@echo "... src/OpenWQ_units.i"
	@echo "... src/OpenWQ_units.s"
	@echo "... src/OpenWQ_watertransp.o"
	@echo "... src/OpenWQ_watertransp.i"
	@echo "... src/OpenWQ_watertransp.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

